// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_node.proto

#ifndef PROTOBUF_INCLUDED_work_5fnode_2eproto
#define PROTOBUF_INCLUDED_work_5fnode_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "shard.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_work_5fnode_2eproto 

namespace protobuf_work_5fnode_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_work_5fnode_2eproto
namespace elasticfaiss {
class CreateShardRequest;
class CreateShardRequestDefaultTypeInternal;
extern CreateShardRequestDefaultTypeInternal _CreateShardRequest_default_instance_;
class CreateShardResponse;
class CreateShardResponseDefaultTypeInternal;
extern CreateShardResponseDefaultTypeInternal _CreateShardResponse_default_instance_;
class DeleteShardRequest;
class DeleteShardRequestDefaultTypeInternal;
extern DeleteShardRequestDefaultTypeInternal _DeleteShardRequest_default_instance_;
class DeleteShardResponse;
class DeleteShardResponseDefaultTypeInternal;
extern DeleteShardResponseDefaultTypeInternal _DeleteShardResponse_default_instance_;
class WorkNodeInitConf;
class WorkNodeInitConfDefaultTypeInternal;
extern WorkNodeInitConfDefaultTypeInternal _WorkNodeInitConf_default_instance_;
}  // namespace elasticfaiss
namespace google {
namespace protobuf {
template<> ::elasticfaiss::CreateShardRequest* Arena::CreateMaybeMessage<::elasticfaiss::CreateShardRequest>(Arena*);
template<> ::elasticfaiss::CreateShardResponse* Arena::CreateMaybeMessage<::elasticfaiss::CreateShardResponse>(Arena*);
template<> ::elasticfaiss::DeleteShardRequest* Arena::CreateMaybeMessage<::elasticfaiss::DeleteShardRequest>(Arena*);
template<> ::elasticfaiss::DeleteShardResponse* Arena::CreateMaybeMessage<::elasticfaiss::DeleteShardResponse>(Arena*);
template<> ::elasticfaiss::WorkNodeInitConf* Arena::CreateMaybeMessage<::elasticfaiss::WorkNodeInitConf>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace elasticfaiss {

// ===================================================================

class CreateShardRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:elasticfaiss.CreateShardRequest) */ {
 public:
  CreateShardRequest();
  virtual ~CreateShardRequest();

  CreateShardRequest(const CreateShardRequest& from);

  inline CreateShardRequest& operator=(const CreateShardRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateShardRequest(CreateShardRequest&& from) noexcept
    : CreateShardRequest() {
    *this = ::std::move(from);
  }

  inline CreateShardRequest& operator=(CreateShardRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateShardRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateShardRequest* internal_default_instance() {
    return reinterpret_cast<const CreateShardRequest*>(
               &_CreateShardRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CreateShardRequest* other);
  friend void swap(CreateShardRequest& a, CreateShardRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateShardRequest* New() const final {
    return CreateMaybeMessage<CreateShardRequest>(NULL);
  }

  CreateShardRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateShardRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateShardRequest& from);
  void MergeFrom(const CreateShardRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateShardRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cluster = 1;
  bool has_cluster() const;
  void clear_cluster();
  static const int kClusterFieldNumber = 1;
  const ::std::string& cluster() const;
  void set_cluster(const ::std::string& value);
  #if LANG_CXX11
  void set_cluster(::std::string&& value);
  #endif
  void set_cluster(const char* value);
  void set_cluster(const char* value, size_t size);
  ::std::string* mutable_cluster();
  ::std::string* release_cluster();
  void set_allocated_cluster(::std::string* cluster);

  // required string shard_nodes = 4;
  bool has_shard_nodes() const;
  void clear_shard_nodes();
  static const int kShardNodesFieldNumber = 4;
  const ::std::string& shard_nodes() const;
  void set_shard_nodes(const ::std::string& value);
  #if LANG_CXX11
  void set_shard_nodes(::std::string&& value);
  #endif
  void set_shard_nodes(const char* value);
  void set_shard_nodes(const char* value, size_t size);
  ::std::string* mutable_shard_nodes();
  ::std::string* release_shard_nodes();
  void set_allocated_shard_nodes(::std::string* shard_nodes);

  // required .elasticfaiss.IndexConf conf = 2;
  bool has_conf() const;
  void clear_conf();
  static const int kConfFieldNumber = 2;
  private:
  const ::elasticfaiss::IndexConf& _internal_conf() const;
  public:
  const ::elasticfaiss::IndexConf& conf() const;
  ::elasticfaiss::IndexConf* release_conf();
  ::elasticfaiss::IndexConf* mutable_conf();
  void set_allocated_conf(::elasticfaiss::IndexConf* conf);

  // required int32 idx = 3;
  bool has_idx() const;
  void clear_idx();
  static const int kIdxFieldNumber = 3;
  ::google::protobuf::int32 idx() const;
  void set_idx(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:elasticfaiss.CreateShardRequest)
 private:
  void set_has_cluster();
  void clear_has_cluster();
  void set_has_conf();
  void clear_has_conf();
  void set_has_idx();
  void clear_has_idx();
  void set_has_shard_nodes();
  void clear_has_shard_nodes();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cluster_;
  ::google::protobuf::internal::ArenaStringPtr shard_nodes_;
  ::elasticfaiss::IndexConf* conf_;
  ::google::protobuf::int32 idx_;
  friend struct ::protobuf_work_5fnode_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateShardResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:elasticfaiss.CreateShardResponse) */ {
 public:
  CreateShardResponse();
  virtual ~CreateShardResponse();

  CreateShardResponse(const CreateShardResponse& from);

  inline CreateShardResponse& operator=(const CreateShardResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateShardResponse(CreateShardResponse&& from) noexcept
    : CreateShardResponse() {
    *this = ::std::move(from);
  }

  inline CreateShardResponse& operator=(CreateShardResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateShardResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateShardResponse* internal_default_instance() {
    return reinterpret_cast<const CreateShardResponse*>(
               &_CreateShardResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CreateShardResponse* other);
  friend void swap(CreateShardResponse& a, CreateShardResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateShardResponse* New() const final {
    return CreateMaybeMessage<CreateShardResponse>(NULL);
  }

  CreateShardResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateShardResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateShardResponse& from);
  void MergeFrom(const CreateShardResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateShardResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string error = 3;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // required bool success = 1;
  bool has_success() const;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:elasticfaiss.CreateShardResponse)
 private:
  void set_has_success();
  void clear_has_success();
  void set_has_error();
  void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  bool success_;
  friend struct ::protobuf_work_5fnode_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WorkNodeInitConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:elasticfaiss.WorkNodeInitConf) */ {
 public:
  WorkNodeInitConf();
  virtual ~WorkNodeInitConf();

  WorkNodeInitConf(const WorkNodeInitConf& from);

  inline WorkNodeInitConf& operator=(const WorkNodeInitConf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WorkNodeInitConf(WorkNodeInitConf&& from) noexcept
    : WorkNodeInitConf() {
    *this = ::std::move(from);
  }

  inline WorkNodeInitConf& operator=(WorkNodeInitConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkNodeInitConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WorkNodeInitConf* internal_default_instance() {
    return reinterpret_cast<const WorkNodeInitConf*>(
               &_WorkNodeInitConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(WorkNodeInitConf* other);
  friend void swap(WorkNodeInitConf& a, WorkNodeInitConf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WorkNodeInitConf* New() const final {
    return CreateMaybeMessage<WorkNodeInitConf>(NULL);
  }

  WorkNodeInitConf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WorkNodeInitConf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WorkNodeInitConf& from);
  void MergeFrom(const WorkNodeInitConf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WorkNodeInitConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .elasticfaiss.CreateShardRequest shards = 1;
  int shards_size() const;
  void clear_shards();
  static const int kShardsFieldNumber = 1;
  ::elasticfaiss::CreateShardRequest* mutable_shards(int index);
  ::google::protobuf::RepeatedPtrField< ::elasticfaiss::CreateShardRequest >*
      mutable_shards();
  const ::elasticfaiss::CreateShardRequest& shards(int index) const;
  ::elasticfaiss::CreateShardRequest* add_shards();
  const ::google::protobuf::RepeatedPtrField< ::elasticfaiss::CreateShardRequest >&
      shards() const;

  // @@protoc_insertion_point(class_scope:elasticfaiss.WorkNodeInitConf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::elasticfaiss::CreateShardRequest > shards_;
  friend struct ::protobuf_work_5fnode_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteShardRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:elasticfaiss.DeleteShardRequest) */ {
 public:
  DeleteShardRequest();
  virtual ~DeleteShardRequest();

  DeleteShardRequest(const DeleteShardRequest& from);

  inline DeleteShardRequest& operator=(const DeleteShardRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteShardRequest(DeleteShardRequest&& from) noexcept
    : DeleteShardRequest() {
    *this = ::std::move(from);
  }

  inline DeleteShardRequest& operator=(DeleteShardRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteShardRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteShardRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteShardRequest*>(
               &_DeleteShardRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DeleteShardRequest* other);
  friend void swap(DeleteShardRequest& a, DeleteShardRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteShardRequest* New() const final {
    return CreateMaybeMessage<DeleteShardRequest>(NULL);
  }

  DeleteShardRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteShardRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteShardRequest& from);
  void MergeFrom(const DeleteShardRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteShardRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cluster = 1;
  bool has_cluster() const;
  void clear_cluster();
  static const int kClusterFieldNumber = 1;
  const ::std::string& cluster() const;
  void set_cluster(const ::std::string& value);
  #if LANG_CXX11
  void set_cluster(::std::string&& value);
  #endif
  void set_cluster(const char* value);
  void set_cluster(const char* value, size_t size);
  ::std::string* mutable_cluster();
  ::std::string* release_cluster();
  void set_allocated_cluster(::std::string* cluster);

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 idx = 3;
  bool has_idx() const;
  void clear_idx();
  static const int kIdxFieldNumber = 3;
  ::google::protobuf::int32 idx() const;
  void set_idx(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:elasticfaiss.DeleteShardRequest)
 private:
  void set_has_cluster();
  void clear_has_cluster();
  void set_has_name();
  void clear_has_name();
  void set_has_idx();
  void clear_has_idx();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cluster_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 idx_;
  friend struct ::protobuf_work_5fnode_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteShardResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:elasticfaiss.DeleteShardResponse) */ {
 public:
  DeleteShardResponse();
  virtual ~DeleteShardResponse();

  DeleteShardResponse(const DeleteShardResponse& from);

  inline DeleteShardResponse& operator=(const DeleteShardResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteShardResponse(DeleteShardResponse&& from) noexcept
    : DeleteShardResponse() {
    *this = ::std::move(from);
  }

  inline DeleteShardResponse& operator=(DeleteShardResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteShardResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteShardResponse* internal_default_instance() {
    return reinterpret_cast<const DeleteShardResponse*>(
               &_DeleteShardResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DeleteShardResponse* other);
  friend void swap(DeleteShardResponse& a, DeleteShardResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteShardResponse* New() const final {
    return CreateMaybeMessage<DeleteShardResponse>(NULL);
  }

  DeleteShardResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeleteShardResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeleteShardResponse& from);
  void MergeFrom(const DeleteShardResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteShardResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string error = 3;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // required bool success = 1;
  bool has_success() const;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:elasticfaiss.DeleteShardResponse)
 private:
  void set_has_success();
  void clear_has_success();
  void set_has_error();
  void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  bool success_;
  friend struct ::protobuf_work_5fnode_2eproto::TableStruct;
};
// ===================================================================

class WorkNodeService_Stub;

class WorkNodeService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorkNodeService() {};
 public:
  virtual ~WorkNodeService();

  typedef WorkNodeService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void create_shard(::google::protobuf::RpcController* controller,
                       const ::elasticfaiss::CreateShardRequest* request,
                       ::elasticfaiss::CreateShardResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void delete_shard(::google::protobuf::RpcController* controller,
                       const ::elasticfaiss::DeleteShardRequest* request,
                       ::elasticfaiss::DeleteShardResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkNodeService);
};

class WorkNodeService_Stub : public WorkNodeService {
 public:
  WorkNodeService_Stub(::google::protobuf::RpcChannel* channel);
  WorkNodeService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~WorkNodeService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements WorkNodeService ------------------------------------------

  void create_shard(::google::protobuf::RpcController* controller,
                       const ::elasticfaiss::CreateShardRequest* request,
                       ::elasticfaiss::CreateShardResponse* response,
                       ::google::protobuf::Closure* done);
  void delete_shard(::google::protobuf::RpcController* controller,
                       const ::elasticfaiss::DeleteShardRequest* request,
                       ::elasticfaiss::DeleteShardResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkNodeService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateShardRequest

// required string cluster = 1;
inline bool CreateShardRequest::has_cluster() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateShardRequest::set_has_cluster() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateShardRequest::clear_has_cluster() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateShardRequest::clear_cluster() {
  cluster_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cluster();
}
inline const ::std::string& CreateShardRequest::cluster() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardRequest.cluster)
  return cluster_.GetNoArena();
}
inline void CreateShardRequest::set_cluster(const ::std::string& value) {
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.CreateShardRequest.cluster)
}
#if LANG_CXX11
inline void CreateShardRequest::set_cluster(::std::string&& value) {
  set_has_cluster();
  cluster_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.CreateShardRequest.cluster)
}
#endif
inline void CreateShardRequest::set_cluster(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.CreateShardRequest.cluster)
}
inline void CreateShardRequest::set_cluster(const char* value, size_t size) {
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.CreateShardRequest.cluster)
}
inline ::std::string* CreateShardRequest::mutable_cluster() {
  set_has_cluster();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.CreateShardRequest.cluster)
  return cluster_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateShardRequest::release_cluster() {
  // @@protoc_insertion_point(field_release:elasticfaiss.CreateShardRequest.cluster)
  if (!has_cluster()) {
    return NULL;
  }
  clear_has_cluster();
  return cluster_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateShardRequest::set_allocated_cluster(::std::string* cluster) {
  if (cluster != NULL) {
    set_has_cluster();
  } else {
    clear_has_cluster();
  }
  cluster_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cluster);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.CreateShardRequest.cluster)
}

// required .elasticfaiss.IndexConf conf = 2;
inline bool CreateShardRequest::has_conf() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CreateShardRequest::set_has_conf() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CreateShardRequest::clear_has_conf() {
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::elasticfaiss::IndexConf& CreateShardRequest::_internal_conf() const {
  return *conf_;
}
inline const ::elasticfaiss::IndexConf& CreateShardRequest::conf() const {
  const ::elasticfaiss::IndexConf* p = conf_;
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardRequest.conf)
  return p != NULL ? *p : *reinterpret_cast<const ::elasticfaiss::IndexConf*>(
      &::elasticfaiss::_IndexConf_default_instance_);
}
inline ::elasticfaiss::IndexConf* CreateShardRequest::release_conf() {
  // @@protoc_insertion_point(field_release:elasticfaiss.CreateShardRequest.conf)
  clear_has_conf();
  ::elasticfaiss::IndexConf* temp = conf_;
  conf_ = NULL;
  return temp;
}
inline ::elasticfaiss::IndexConf* CreateShardRequest::mutable_conf() {
  set_has_conf();
  if (conf_ == NULL) {
    auto* p = CreateMaybeMessage<::elasticfaiss::IndexConf>(GetArenaNoVirtual());
    conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:elasticfaiss.CreateShardRequest.conf)
  return conf_;
}
inline void CreateShardRequest::set_allocated_conf(::elasticfaiss::IndexConf* conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(conf_);
  }
  if (conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conf, submessage_arena);
    }
    set_has_conf();
  } else {
    clear_has_conf();
  }
  conf_ = conf;
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.CreateShardRequest.conf)
}

// required int32 idx = 3;
inline bool CreateShardRequest::has_idx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CreateShardRequest::set_has_idx() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CreateShardRequest::clear_has_idx() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CreateShardRequest::clear_idx() {
  idx_ = 0;
  clear_has_idx();
}
inline ::google::protobuf::int32 CreateShardRequest::idx() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardRequest.idx)
  return idx_;
}
inline void CreateShardRequest::set_idx(::google::protobuf::int32 value) {
  set_has_idx();
  idx_ = value;
  // @@protoc_insertion_point(field_set:elasticfaiss.CreateShardRequest.idx)
}

// required string shard_nodes = 4;
inline bool CreateShardRequest::has_shard_nodes() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateShardRequest::set_has_shard_nodes() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateShardRequest::clear_has_shard_nodes() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateShardRequest::clear_shard_nodes() {
  shard_nodes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shard_nodes();
}
inline const ::std::string& CreateShardRequest::shard_nodes() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardRequest.shard_nodes)
  return shard_nodes_.GetNoArena();
}
inline void CreateShardRequest::set_shard_nodes(const ::std::string& value) {
  set_has_shard_nodes();
  shard_nodes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.CreateShardRequest.shard_nodes)
}
#if LANG_CXX11
inline void CreateShardRequest::set_shard_nodes(::std::string&& value) {
  set_has_shard_nodes();
  shard_nodes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.CreateShardRequest.shard_nodes)
}
#endif
inline void CreateShardRequest::set_shard_nodes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_shard_nodes();
  shard_nodes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.CreateShardRequest.shard_nodes)
}
inline void CreateShardRequest::set_shard_nodes(const char* value, size_t size) {
  set_has_shard_nodes();
  shard_nodes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.CreateShardRequest.shard_nodes)
}
inline ::std::string* CreateShardRequest::mutable_shard_nodes() {
  set_has_shard_nodes();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.CreateShardRequest.shard_nodes)
  return shard_nodes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateShardRequest::release_shard_nodes() {
  // @@protoc_insertion_point(field_release:elasticfaiss.CreateShardRequest.shard_nodes)
  if (!has_shard_nodes()) {
    return NULL;
  }
  clear_has_shard_nodes();
  return shard_nodes_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateShardRequest::set_allocated_shard_nodes(::std::string* shard_nodes) {
  if (shard_nodes != NULL) {
    set_has_shard_nodes();
  } else {
    clear_has_shard_nodes();
  }
  shard_nodes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shard_nodes);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.CreateShardRequest.shard_nodes)
}

// -------------------------------------------------------------------

// CreateShardResponse

// required bool success = 1;
inline bool CreateShardResponse::has_success() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateShardResponse::set_has_success() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateShardResponse::clear_has_success() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateShardResponse::clear_success() {
  success_ = false;
  clear_has_success();
}
inline bool CreateShardResponse::success() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardResponse.success)
  return success_;
}
inline void CreateShardResponse::set_success(bool value) {
  set_has_success();
  success_ = value;
  // @@protoc_insertion_point(field_set:elasticfaiss.CreateShardResponse.success)
}

// optional string error = 3;
inline bool CreateShardResponse::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateShardResponse::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateShardResponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateShardResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& CreateShardResponse::error() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.CreateShardResponse.error)
  return error_.GetNoArena();
}
inline void CreateShardResponse::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.CreateShardResponse.error)
}
#if LANG_CXX11
inline void CreateShardResponse::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.CreateShardResponse.error)
}
#endif
inline void CreateShardResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.CreateShardResponse.error)
}
inline void CreateShardResponse::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.CreateShardResponse.error)
}
inline ::std::string* CreateShardResponse::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.CreateShardResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateShardResponse::release_error() {
  // @@protoc_insertion_point(field_release:elasticfaiss.CreateShardResponse.error)
  if (!has_error()) {
    return NULL;
  }
  clear_has_error();
  return error_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateShardResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.CreateShardResponse.error)
}

// -------------------------------------------------------------------

// WorkNodeInitConf

// repeated .elasticfaiss.CreateShardRequest shards = 1;
inline int WorkNodeInitConf::shards_size() const {
  return shards_.size();
}
inline void WorkNodeInitConf::clear_shards() {
  shards_.Clear();
}
inline ::elasticfaiss::CreateShardRequest* WorkNodeInitConf::mutable_shards(int index) {
  // @@protoc_insertion_point(field_mutable:elasticfaiss.WorkNodeInitConf.shards)
  return shards_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::elasticfaiss::CreateShardRequest >*
WorkNodeInitConf::mutable_shards() {
  // @@protoc_insertion_point(field_mutable_list:elasticfaiss.WorkNodeInitConf.shards)
  return &shards_;
}
inline const ::elasticfaiss::CreateShardRequest& WorkNodeInitConf::shards(int index) const {
  // @@protoc_insertion_point(field_get:elasticfaiss.WorkNodeInitConf.shards)
  return shards_.Get(index);
}
inline ::elasticfaiss::CreateShardRequest* WorkNodeInitConf::add_shards() {
  // @@protoc_insertion_point(field_add:elasticfaiss.WorkNodeInitConf.shards)
  return shards_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::elasticfaiss::CreateShardRequest >&
WorkNodeInitConf::shards() const {
  // @@protoc_insertion_point(field_list:elasticfaiss.WorkNodeInitConf.shards)
  return shards_;
}

// -------------------------------------------------------------------

// DeleteShardRequest

// required string cluster = 1;
inline bool DeleteShardRequest::has_cluster() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteShardRequest::set_has_cluster() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteShardRequest::clear_has_cluster() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteShardRequest::clear_cluster() {
  cluster_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cluster();
}
inline const ::std::string& DeleteShardRequest::cluster() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.DeleteShardRequest.cluster)
  return cluster_.GetNoArena();
}
inline void DeleteShardRequest::set_cluster(const ::std::string& value) {
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.DeleteShardRequest.cluster)
}
#if LANG_CXX11
inline void DeleteShardRequest::set_cluster(::std::string&& value) {
  set_has_cluster();
  cluster_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.DeleteShardRequest.cluster)
}
#endif
inline void DeleteShardRequest::set_cluster(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.DeleteShardRequest.cluster)
}
inline void DeleteShardRequest::set_cluster(const char* value, size_t size) {
  set_has_cluster();
  cluster_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.DeleteShardRequest.cluster)
}
inline ::std::string* DeleteShardRequest::mutable_cluster() {
  set_has_cluster();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.DeleteShardRequest.cluster)
  return cluster_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteShardRequest::release_cluster() {
  // @@protoc_insertion_point(field_release:elasticfaiss.DeleteShardRequest.cluster)
  if (!has_cluster()) {
    return NULL;
  }
  clear_has_cluster();
  return cluster_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteShardRequest::set_allocated_cluster(::std::string* cluster) {
  if (cluster != NULL) {
    set_has_cluster();
  } else {
    clear_has_cluster();
  }
  cluster_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cluster);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.DeleteShardRequest.cluster)
}

// required string name = 2;
inline bool DeleteShardRequest::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeleteShardRequest::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeleteShardRequest::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeleteShardRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& DeleteShardRequest::name() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.DeleteShardRequest.name)
  return name_.GetNoArena();
}
inline void DeleteShardRequest::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.DeleteShardRequest.name)
}
#if LANG_CXX11
inline void DeleteShardRequest::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.DeleteShardRequest.name)
}
#endif
inline void DeleteShardRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.DeleteShardRequest.name)
}
inline void DeleteShardRequest::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.DeleteShardRequest.name)
}
inline ::std::string* DeleteShardRequest::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.DeleteShardRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteShardRequest::release_name() {
  // @@protoc_insertion_point(field_release:elasticfaiss.DeleteShardRequest.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteShardRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.DeleteShardRequest.name)
}

// required int32 idx = 3;
inline bool DeleteShardRequest::has_idx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DeleteShardRequest::set_has_idx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DeleteShardRequest::clear_has_idx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DeleteShardRequest::clear_idx() {
  idx_ = 0;
  clear_has_idx();
}
inline ::google::protobuf::int32 DeleteShardRequest::idx() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.DeleteShardRequest.idx)
  return idx_;
}
inline void DeleteShardRequest::set_idx(::google::protobuf::int32 value) {
  set_has_idx();
  idx_ = value;
  // @@protoc_insertion_point(field_set:elasticfaiss.DeleteShardRequest.idx)
}

// -------------------------------------------------------------------

// DeleteShardResponse

// required bool success = 1;
inline bool DeleteShardResponse::has_success() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeleteShardResponse::set_has_success() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeleteShardResponse::clear_has_success() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeleteShardResponse::clear_success() {
  success_ = false;
  clear_has_success();
}
inline bool DeleteShardResponse::success() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.DeleteShardResponse.success)
  return success_;
}
inline void DeleteShardResponse::set_success(bool value) {
  set_has_success();
  success_ = value;
  // @@protoc_insertion_point(field_set:elasticfaiss.DeleteShardResponse.success)
}

// optional string error = 3;
inline bool DeleteShardResponse::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteShardResponse::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteShardResponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteShardResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& DeleteShardResponse::error() const {
  // @@protoc_insertion_point(field_get:elasticfaiss.DeleteShardResponse.error)
  return error_.GetNoArena();
}
inline void DeleteShardResponse::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:elasticfaiss.DeleteShardResponse.error)
}
#if LANG_CXX11
inline void DeleteShardResponse::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:elasticfaiss.DeleteShardResponse.error)
}
#endif
inline void DeleteShardResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:elasticfaiss.DeleteShardResponse.error)
}
inline void DeleteShardResponse::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:elasticfaiss.DeleteShardResponse.error)
}
inline ::std::string* DeleteShardResponse::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:elasticfaiss.DeleteShardResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteShardResponse::release_error() {
  // @@protoc_insertion_point(field_release:elasticfaiss.DeleteShardResponse.error)
  if (!has_error()) {
    return NULL;
  }
  clear_has_error();
  return error_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteShardResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:elasticfaiss.DeleteShardResponse.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace elasticfaiss

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_work_5fnode_2eproto
